Repository taia-x/taia-x, pull requests merged in 2021-11, with the labels that each got.

#30 19 provider template
  .github/workflows/test.yml
  .gitignore
  .vscode/launch.json
  provider/Dockerfile
  provider/README.md
  provider/main.py
  provider/requirements.txt
  provider/test_main.py
Labels: devops, backend

#32 31 frontend template
  frontend/.browserslistrc
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/README.md
  frontend/babel.config.js
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.vue
  frontend/src/assets/css/tailwind.css
  frontend/src/assets/logo.png
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/services/wallet-service.ts
  frontend/src/shims-vue.d.ts
  frontend/src/stores/useUser.ts
  frontend/src/types/contract.ts
  frontend/src/views/Home.vue
  frontend/tailwind.config.js
  frontend/tests/unit/example.spec.ts
  frontend/tsconfig.json
  frontend/vue.config.js
Labels: frontend

#33 20 dummy dataset
  .gitignore
  dummy-files/__init__.py
  dummy-files/main.py
  dummy-files/sensordata/Sensors/__init__.py
  dummy-files/sensordata/Sensors/battery_sensor.py
  dummy-files/sensordata/Sensors/camera.py
  dummy-files/sensordata/Sensors/gnss_sensor.py
  dummy-files/sensordata/Sensors/imu_sensor.py
  dummy-files/sensordata/Sensors/lidar_sensor.py
  dummy-files/sensordata/Sensors/radar_sensor.py
  dummy-files/sensordata/Sensors/semantic_lidar_sensor.py
  dummy-files/sensordata/__init__.py
  dummy-files/sensordata/location.py
  dummy-files/sensordata/rotation.py
  dummy-files/sensordata/sensordata.py
Labels: backend

#61 #24 certifier can upload ontologies
  .github/workflows/test-backend.yml
  .github/workflows/test.yml
  .gitignore
  .vscode/launch.json
  backend/.env.template
  backend/Dockerfile
  backend/README.md
  backend/app/__init__.py
  backend/app/core/__init__.py
  backend/app/core/config.py
  backend/app/core/ipfs.py
  backend/app/core/test_ipfs.py
  backend/app/db.py
  backend/app/main.py
  backend/app/models.py
  backend/app/routers/__init__.py
  backend/app/routers/ontologies.py
  backend/app/routers/test_ontologies.py
  backend/app/schemas.py
  backend/app/test_main.py
  backend/docker-start.sh
  backend/requirements.txt
  docker-compose.yml
  provider/Dockerfile
  provider/README.md
  provider/requirements.txt
Labels: devops, backend

#74 67 ontology standard
  dummy-files/main.py
  dummy-files/ontology-standard/README.md
  dummy-files/ontology-standard/battery.json
  dummy-files/ontology-standard/camera.json
  dummy-files/ontology-standard/gnss.json
  dummy-files/ontology-standard/imu.json
  dummy-files/ontology-standard/lidar.json
  dummy-files/ontology-standard/radar.json
  dummy-files/ontology-standard/slidar.json
  dummy-files/ontology-standard/vehicle.json
  dummy-files/sensordata/Sensors/battery_sensor.py
  dummy-files/sensordata/Sensors/camera.py
  dummy-files/sensordata/Sensors/gnss_sensor.py
  dummy-files/sensordata/Sensors/imu_sensor.py
  dummy-files/sensordata/Sensors/lidar_sensor.py
  dummy-files/sensordata/Sensors/radar_sensor.py
  dummy-files/sensordata/Sensors/semantic_lidar_sensor.py
Labels: documentation, enhancement, backend

#69 21 setup local environment
  README.md
  contracts/.env.template
  docker-compose.yml
Labels: devops
